micronaut:
  application:
    name: shared-calendar
  router:
    static-resources:
      default:
        mapping: /**
        paths: classpath:public
        enabled: 'true'
  server:
    cors:
      enabled: 'true'
datasources:
  default:
    url: jdbc:h2:file:./data/app_db;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: ""
    dialect: H2

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: false

dropbox:
  auth:
    key: dropboxAppKey
    secret: dropboxAppSecret